name: myhomework
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ—ºï¸ Google Maps & Location
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2

  # ğŸŒ Network
  http: ^1.1.0

  # ğŸ§­ State Management & Routing
  get: ^4.7.2

  # ğŸ”¥ Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.0

  # ğŸ¨ UI & Fonts
  google_fonts: ^6.2.1
  animate_do: ^3.1.2
  flutter_image_slideshow: ^0.1.6
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.8

  # ğŸ–¼ï¸ Image Picker
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ğŸ§© Build Tools
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    # á”á“áŸ’ááŸ‚á˜á”á¶á“á”á¾á˜á¶á“ folder á•áŸ’áŸáŸá„áŸ—
    # - assets/images/
    # - assets/icons/
